### ISSUE TITLE
Ability to exclude XCUIElements from being tapped

### ISSUE THREAD

**Issue by deemicksee** [zalando/SwiftMonkey#44]
Firstly, thanks for this, it's a great tool, working generally fairly well for me in the few test runs I've used it for.

Secondly, apologies if this is covered in the framework already, I took a look at the Monkey.swift file and could see randomPointAvoidingPanelAreas, but that's not quite what I'd be after here (I think!)

**Context for my request:**
There's a few parts of my app I don't want the 'monkey' to tap: eg, links to webviews (which open Safari), links to other apps (eg: out to Maps), log out buttons (which we'd normally not want tapped, as our app largely needs to be tested while 'logged-in'), or even debug-build specific tap areas where we nest 'admin' functionality, etc, etc. When the 'monkey' taps these areas, the test is either invalid (I don't want the 'monkey' testing Apple Maps), or becomes not as interesting to me (eg: if logged-out, I don't care as much about what the 'monkey' finds)

**Request:**
- Create a dictionary of items that need to be ignored by the 'monkey', perhaps as a list of XCUIElements.
- Have the 'monkey' check for existence of items in this dictionary, and avoid these if the dictionary's populated
- Continue on as-usual, if nothing's in the dictionary?
Or something like that maybe? The gist is: a way to exclude specific XCUIElements from tap events.

**Comment by wojciechczerski** [comment]
Hello @deemicksee and than you for using and contributing to SwiftMonkey!

The problem you have described is very interesting and challenging. The `XCUIElement` has a `frame` property that would be the screen area we do not want to tap. So if you provide a list of such elements we could exclude their areas when generating a random _tap point_.

Please give me some time to experiment with possible solutions. I hope to get back to you with some results and maybe even with a _feature branch_ to test 😄

**Comment by deemicksee** [comment]
Wow, excellent, that'd be great thanks. Please let me know if I can help with the testing of it.

**Comment by DagAgren** [comment]
The problem here is that accessing properties of XCUIElements is very, very slow. So anything that needs to deal with XCUIElements at each click will basically grind the testing to a halt. This is why the code does not use public XCTest APIs at all.

**Comment by wojciechczerski** [comment]
Hey @DagAgren, @deemicksee ! Indeed accessing the `frame` property is really slow. I was however able to "solve" this by computing the area for tapping once and then using it when a random _tap_ point needs to be generated. This however is not perfect since the position of an `XCUIElement` might change (scrolling) and then the pre-computed area is not valid anymore.

To demonstrate how it works, you can checkout [this](https://github.com/zalando/SwiftMonkey/tree/feature/tap-excluded-elements) feature branch. It has a pre configured sample that sets Monkey to only generate tap actions. It also excludes from tapping all buttons except the "OK button" and the 2 bottom tab bar items. The result is that when the tests are running only the "OK button" gets tapped and the `BananaViewController` is never shown.

I would greatly appreciate if you could have a look at this implementation. I am not sure if it brings any value in the current state (works only for static `XCUIElement` objects). It should be fine to use it for disabling tapping on `Cancel`, `Done`, etc. buttons that would dismiss the tested screen. However as soon as someone uses it on a scrolling content - it becomes _broken_.

I wonder if there is a more optimal way of getting the `frame`? Or maybe detecting that the frame has changed and it should be queried again?


**Side note**

The algorithm works by dividing the frame into smaller rectangles and removing those that intersect with the _tap excluded_ frames. This image should clarify it:

![bildschirmfoto 2017-10-22 um 22 32 35](https://user-images.githubusercontent.com/1027098/31866135-fe610020-b77a-11e7-8cc5-3f7c7c5069f1.png)

If you call `rect.divided(toExclude: [...])` you will get a list of _orange_ rectangles. Then you need to pick a random _orange_ rectangle, generate a random `CGPoint` within it and voilà! You have a random point that doesn't intersect with `UIButton` nor `UISwitch` frames.

**Comment by wojciechczerski** [comment]
I thought about this feature and with the limitations we currently have a reasonable scope of it is to:

> Globally block certain parts of the screen from being tapped by SwiftMonkey.

This means that an API that accepts an array of `XCUIElement` is misleading and instead it should just take a `CGRect` collection.

**Comment by deemicksee** [comment]
Hey team, apologies for the delay in replying here, I've been busy with a newborn ;)

Some extra context: in the app I'm testing at the moment, there are maybe ~50 elements I do not want tapped, and ~5000 ones I _do_ want tapped. The app has pages that go about as deep as 8 pages away from the home-screen at any time

Here's my feedback on the tap-excluded-elements branch:

- [ ]  my app supports as far back as iOS 8. With this branch though, I had to edit these files locally, to add: “@available(iOS 9.0, *)” to the top of Monkey.swift + MonkeyUIAutomation.swift + MonkeyXCTestPrivate.swift. Is it possible to add those permanently in that branch?

- [ ] I might be missing something important here, but it looks like this only really works on a single-page app. Scenario: I need to exclude different items on pages 2, 3, and 4, and I set the monkey off on page 1; I don't know when the monkey will get to pages 2, 3, and/or 4. At present, the tests fail for me, because the excluded items in pages 2,3,4 can't be found when I start the testing at page 1. XCode logs:
"No matches found for Find: Descendants matching type Table from input {(
    Application, 0x6080001893e0, pid: 82352, label: 'My App'
)}"
I can't think of many ways around this; it is essentially the same problem as the 'scrolling' one that @wojciechczerski mentioned above. We'd need to have a way to redraw the screen's rectangles _and_ the list of elements to exclude

- [ ] it's possible I'm misunderstanding what's been done here, but I think monkey.tapExcluded should be named monkey.tapOnlyTheseElements or something like that? It looks like the list works the opposite of what I was hoping for: the monkey uses tapExcluded to only tap the things it's told to tap. 

- [ ] As a follow-up to this ^, I can make the current code work, but I'd prefer to have a small list of elements to exclude tapping, rather than a large list of elements we want the monkey to tap

Hopefully that feedback makes sense. I appreciate the effort put in to get us this far! I think it's fairly close here, but might only work usefully as-implemented on single-page apps that don't change the UI too much?

**Comment by wojciechczerski** [comment]
Hi, and thanks for the feedback! Regarding your questions:

The deployment target was set to 9.0 because this is required for using the `XCUIElement` class. This however might be changed because the implemented solution doesn't really work with `XCUIElement` objects but instead with `CGRect` collection that is _extracted_ from the given elements to exclude using the `frame` property.

Unfortunately this is a _one-screen-solution_ or if you rephrase it _one-solution-for-all-screens_. To make it really dynamic we'd have to query the `frame` property each time a random point to tap is generated - this will kill the performance because each query to `XCUIElement` or its properties is very slow.
This issue seems to be a real blocker for making this feature useful and unfortunately I don't have any good ideas on how to proceed.

The `tapExcluded` collection should contain elements you wish **NOT** to tap. The code should work like that - are you observing a different behavior?

I could change the interface for this feature to `var tapExcluded: [CGRect]` to clearly indicate that it works with static frames. The question is whether or not such feature is useful at all. Like you mentioned it would work for single paged apps and also maybe if your app contains some global tap areas (tab bar?) that you wish not to tap. These are however rather extreme use cases.

**Comment by deemicksee** [comment]
Hi there, 

Thanks for the feedback, yeah I agree this idea might be a non-starter in that case.

I've been working on a workaround that seems to be working for me. It uses the main branch of SwiftMonkey, instead of this feature branch. The upshot is: 2 x 'while' loops help me check:
- persistent navigation element is on screen. If it is, then monkey around. After monkeying, return to the app (this will only work on the simulator, but I assume most testing with this tool is done in the simulator?)
- if the monkey got deep within a multi-page app, then move backwards/forwards by interacting with known buttons. I call this a 'sink'; the Monkey is stuck in a sinkhole and needs to escape to provide meaningful test coverage

Here's a dummy version of that code:

```
import XCTest
import SwiftMonkey

class PageObjectTests: BaseTest {
    func testName() {
        let app2 = XCUIApplication()
        // for 10 loops, Monkey around
        var i:Int = 0
        let finishLoop:Int = 10
        while (i <= finishLoop) {
            let myApp = XCUIApplication(bundleIdentifier: "{myBundleName}")
            // if my persistent Nav bar exists, I'm safe to Monkey
            if app2.tabBars.buttons["MyAlwaysPresentNavBar"].exists {
                    _ = app2.descendants(matching: .any).element(boundBy: 0).frame
                    let monkey = Monkey(frame: app2.frame)
                    monkey.addDefaultXCTestPrivateActions()
                    monkey.addXCTestTapAlertAction(interval: 100, application: app2)
                    monkey.monkeyAround(iterations: 20)
                    // Go back to the app at the end of the Monkeying. It's possible a round of Monkeying happens external from the app, but it's not too bad provided you have a few loops of 'while'
                    myApp.activate() // <--- Go back to your app
                }
                    // If my persistent Nav bar doesn't display, we might be trapped in a weird in-app view that doesn't give access to the Nav Bar
                    // This next while loop helps us here to escape 'in-app sinks'
                    // We need to take evasive action to escape an 'in-app sink' able to close that view, but we can't predict where we are so we need a series of if / else' to best-guess how to escape
                else {
                    let listOfButtonsToGetOutOfTheSink = ["Cancel","Back","Continue","Done"]
                    let i2:Int = listOfButtonsToGetOutOfTheSink.count
                    while i2 < 5 {
                            if app2.buttons[listOfButtonsToGetOutOfTheSink[i2]].exists {
                            app2.buttons[listOfButtonsToGetOutOfTheSink[i2]].tap()
                        }
                    }
                }
              i += 1
            }
            print(app2.debugDescription)
            tearDown()
        }
    }
```

Provided there's a good balance between Monkey iterations + numbers set on the initial 'while' then a fair amount of the app can be safely tested. Sometimes the Monkey taps on something that takes the user out to Safari, but now it doesn't matter that much!

That's my best workaround to use this tool, without pushing further on this Feature Branch. I think we can probably close this Issue now, if you agree. Thanks for your efforts, I think they'd work well for anyone in a reliably single-screen app.

Cheers!

**Comment by wojciechczerski** [comment]
Hey! I will close the issue just like you suggested. I think we've reached a good conclusion of not pushing this feature as it is currently not possible to implement it correctly - to be accurate and having good performance.

Thank you very much @deemicksee for an amazing support for the project!
