### ISSUE TITLE
2.0 fails to run for me; error in addXCTestTapAlertAction

### ISSUE THREAD

**Issue by deemicksee** [zalando/SwiftMonkey#51]
Hi team

Congrats on getting 2.0 released, I'm excited to start using it, to remove a few custom hacks for activating the app to the foreground.

I tried to use 2.0 today and my tests fail to build when running it, after a 'pod repo update' + 'pod install'. 

XCode logs a problem with addXCTestTapAlertAction's line:
`                let index = self!.r.randomInt(lessThan: buttons.count)
`
It suggests a fix like this:
`                let index = self!.r.randomInt(lessThan: Int(buttons.count))
`

Have I done something wrong, or is this legit?

Thanks

Daniel

**Comment by wojciechczerski** [comment]
Hi @deemicksee and thanks for an immediate feedback after the new release 😄
Regarding your issue, is it correct that your project is using Swift 3 version? The reason I'm asking is because of what Xcode is suggesting to you. It looks like an exact opposite of what we did to migrate to Swift 4. Look here: https://github.com/zalando/SwiftMonkey/pull/48/files#diff-884f34fe37364def7d3d15c22b1ddd3aL37

The new version 2.0 is **not backwards compatible** (perhaps I should add this info to the release notes) and it supports Swift 4 only (hence the major version bump to 2.0). If this is indeed the case that you have a Swift 3 project and you're using SwiftMonkey 2.0 then we have 2 options:
1. You would have to try migrating to Swift 4 yourself
2. I will add the feature you need to a new version 1.1.1 that will be Swift 3 compatible

What do you think?

**Comment by deemicksee** [comment]
All working now, cheers for the advice @wojciechczerski I think I got confused because the main README.md says "SwiftMonkey uses Swift 3.0." I'll close this issue now, but it'd be great if we could make that line more clear. Sorry for the confusion, and thanks for the upgrade!
