### ISSUE TITLE
 EXC_BAD_ACCESS on addXCTestTapAction

### ISSUE THREAD

**Issue by val0904** [zalando/SwiftMonkey#92]
I'm getting a strange issue 
`let multiTouchMonkey = Monkey(frame: app.frame)
        multiTouchMonkey.addXCTestTapAction(weight: 1, multipleTapProbability: 0.5, multipleTouchProbability: 0.5)
        multiTouchMonkey.monkeyAround(forDuration: 60)`
<img width="1125" alt="Снимок экрана 2020-05-27 в 16 13 24" src="https://user-images.githubusercontent.com/43624245/83023200-420bc580-a035-11ea-9cb0-b33c96c4c7fc.png">

Monkey works properly in other tests but here it always fails on the start. 

Xcode 11.4.1, simulator iPhone SE 2nd generation

**Comment by wojciechczerski** [comment]
Thank you very much for the report @val0904. I have tested it locally and I can reproduce the error. I will try to fix it and will give you an update on the progress.

**Comment by wojciechczerski** [comment]
The source of this issue is the same as mentioned [here](https://github.com/zalando/SwiftMonkey/issues/73). Apple removed the `XCEventGenerator` class that SwiftMonkey was using for event generation. For now, what should work is to use the `addXCTestPublic*` methods. Would it work for you to use the `addXCTestPublicTapAction` method instead?

**Comment by val0904** [comment]
Yes, it does. Thank you!
